### ISSUE TITLE
[Feature Request] Bot should delete command messages

### ISSUE THREAD

**Issue by Dragonsight91** [awkwardartist/VecterBot#1]
quite a simple thing really, i find command messages disruptive to a conversation, the best way to solve this is to delete the user's command message after sending the response

**Comment by awkwardartist** [comment]
> quite a simple thing really, i find command messages disruptive to a conversation, the best way to solve this is to delete the user's command message after sending the response

I actually tried to do this, but something about the permissions did not work out on the official server, but it did however work on the testing server

**Comment by Dragonsight91** [comment]
fair, then ask Tara to get `manage messages` permission, meanwhile i will ... uh... clean this code... and make it about a hundred lines shorter
